//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCwCMS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_MediaGalleries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_MediaGalleries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVCwCMS.Resources.Strings_MediaGalleries", typeof(Strings_MediaGalleries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected the following Media Gallery.
        /// </summary>
        public static string CurrentMediaGallery {
            get {
                return ResourceManager.GetString("CurrentMediaGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the Media Items and press Submit to save.
        /// </summary>
        public static string EditMediaItemsAndSubmit {
            get {
                return ResourceManager.GetString("EditMediaItemsAndSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media galleries.
        /// </summary>
        public static string MediaGalleries {
            get {
                return ResourceManager.GetString("MediaGalleries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit Media gallery.
        /// </summary>
        public static string MediaGalleriesAddEdit {
            get {
                return ResourceManager.GetString("MediaGalleriesAddEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media gallery code.
        /// </summary>
        public static string MediaGalleryCode {
            get {
                return ResourceManager.GetString("MediaGalleryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected media gallery code already exists.
        /// </summary>
        public static string MediaGalleryCodeAlreadyExists {
            get {
                return ResourceManager.GetString("MediaGalleryCodeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media gallery title.
        /// </summary>
        public static string MediaGalleryTitle {
            get {
                return ResourceManager.GetString("MediaGalleryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected media item already exists.
        /// </summary>
        public static string MediaItemAlreadyExists {
            get {
                return ResourceManager.GetString("MediaItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media items.
        /// </summary>
        public static string MediaItems {
            get {
                return ResourceManager.GetString("MediaItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add media items.
        /// </summary>
        public static string MediaItemsAdd {
            get {
                return ResourceManager.GetString("MediaItemsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        public static string MediaItemTitle {
            get {
                return ResourceManager.GetString("MediaItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media type.
        /// </summary>
        public static string MediaTypeName {
            get {
                return ResourceManager.GetString("MediaTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string MediaTypePhoto {
            get {
                return ResourceManager.GetString("MediaTypePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube Video.
        /// </summary>
        public static string MediaTypeYouTubeVideo {
            get {
                return ResourceManager.GetString("MediaTypeYouTubeVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube Videos.
        /// </summary>
        public static string YouTubeVideos {
            get {
                return ResourceManager.GetString("YouTubeVideos", resourceCulture);
            }
        }
    }
}
