//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCwCMS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings_News {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_News() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVCwCMS.Resources.Strings_News", typeof(Strings_News).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Archives.
        /// </summary>
        public static string AllArchives {
            get {
                return ResourceManager.GetString("AllArchives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Categories.
        /// </summary>
        public static string AllCategories {
            get {
                return ResourceManager.GetString("AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archives.
        /// </summary>
        public static string Archives {
            get {
                return ResourceManager.GetString("Archives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category ID.
        /// </summary>
        public static string CategoryId {
            get {
                return ResourceManager.GetString("CategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected category name already exists.
        /// </summary>
        public static string CategoryNameAlreadyExists {
            get {
                return ResourceManager.GetString("CategoryNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your comment. It will be visible soon on this page..
        /// </summary>
        public static string CommentAdded {
            get {
                return ResourceManager.GetString("CommentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve comments automatically.
        /// </summary>
        public static string CommentAutoApproved {
            get {
                return ResourceManager.GetString("CommentAutoApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment date.
        /// </summary>
        public static string CommentDate {
            get {
                return ResourceManager.GetString("CommentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected the following news.
        /// </summary>
        public static string CurrentNews {
            get {
                return ResourceManager.GetString("CurrentNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Here is the latest comment submitted to {$Url}:&lt;/p&gt;
        ///&lt;table style=&quot;border-collapse:collapse;border-spacing:0;width:100%&quot;&gt;
        ///  &lt;tr&gt;
        ///    &lt;th style=&quot;border:1px #bbb solid;padding:10px;text-align:left;vertical-align:top;width:1%;white-space:nowrap;&quot;&gt;Subscription email:&lt;/th&gt;
        ///    &lt;td style=&quot;border:1px #bbb solid;padding:10px;vertical-align:top;&quot;&gt;{$subscriptionEmail}&lt;/td&gt;
        ///  &lt;/tr&gt;
        ///  &lt;tr&gt;
        ///    &lt;th style=&quot;border:1px #bbb solid;padding:10px;text-align:left;vertical-align:top;width:1%;white-space:nowrap;&quot;&gt;Comment [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailBody {
            get {
                return ResourceManager.GetString("EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment submitted to {$Url}.
        /// </summary>
        public static string EmailSubject {
            get {
                return ResourceManager.GetString("EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a Comment.
        /// </summary>
        public static string LeaveAComment {
            get {
                return ResourceManager.GetString("LeaveAComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover photo.
        /// </summary>
        public static string MainImageFilePath {
            get {
                return ResourceManager.GetString("MainImageFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage categories.
        /// </summary>
        public static string ManageNewsCategories {
            get {
                return ResourceManager.GetString("ManageNewsCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit News.
        /// </summary>
        public static string NewsAddEdit {
            get {
                return ResourceManager.GetString("NewsAddEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Categories.
        /// </summary>
        public static string NewsCategories {
            get {
                return ResourceManager.GetString("NewsCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit categories.
        /// </summary>
        public static string NewsCategoriesAddEdit {
            get {
                return ResourceManager.GetString("NewsCategoriesAddEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete category.
        /// </summary>
        public static string NewsCategoriesDelete {
            get {
                return ResourceManager.GetString("NewsCategoriesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string NewsComment {
            get {
                return ResourceManager.GetString("NewsComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string NewsComments {
            get {
                return ResourceManager.GetString("NewsComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit comment.
        /// </summary>
        public static string NewsCommentsEdit {
            get {
                return ResourceManager.GetString("NewsCommentsEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News configuration.
        /// </summary>
        public static string NewsConfiguration {
            get {
                return ResourceManager.GetString("NewsConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        public static string NewsContent {
            get {
                return ResourceManager.GetString("NewsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish date.
        /// </summary>
        public static string NewsDate {
            get {
                return ResourceManager.GetString("NewsDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the offical news feed of {$SiteName}.
        /// </summary>
        public static string NewsFeedDescription {
            get {
                return ResourceManager.GetString("NewsFeedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Feed - {$SiteName}.
        /// </summary>
        public static string NewsFeedTitle {
            get {
                return ResourceManager.GetString("NewsFeedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send as Newsletter.
        /// </summary>
        public static string NewsLetterSend {
            get {
                return ResourceManager.GetString("NewsLetterSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News not found..
        /// </summary>
        public static string NewsNotFound {
            get {
                return ResourceManager.GetString("NewsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News page.
        /// </summary>
        public static string NewsPage {
            get {
                return ResourceManager.GetString("NewsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open this news.
        /// </summary>
        public static string NewsView {
            get {
                return ResourceManager.GetString("NewsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no news to display. Try a different category or archive..
        /// </summary>
        public static string NoNewsToDisplay {
            get {
                return ResourceManager.GetString("NoNewsToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of latest news.
        /// </summary>
        public static string NumberOfNewsInSummary {
            get {
                return ResourceManager.GetString("NumberOfNewsInSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posted on.
        /// </summary>
        public static string PostedOn {
            get {
                return ResourceManager.GetString("PostedOn", resourceCulture);
            }
        }
    }
}
